# Generated by Django 3.2.4 on 2021-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=200, unique=True)),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('percent', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
