# Generated by Django 3.2.4 on 2021-12-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(),
        ),
    ]
