# Generated by Django 3.2.4 on 2021-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
