# Generated by Django 3.2.4 on 2021-12-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211214_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=120),
        ),
    ]
